lshpaner/eda_toolkit

src/eda_toolkit/main.py

Changes Introduced:
1. **Parameter Customization:**
- Introduced a new parameter `num_digits` to allow users to specify the number of digits for the unique IDs.
2. **Improved Default Column Name:**
- Changed the default column name from `Patient_ID` to `ID` to be more generic and widely understood.
- Updated the parameter name from `column_name` to `id_colname` for better clarity and consistency.

added num_dig, changed id_col in add_ids

---

src/eda_toolkit/main.py

**Changes Introduced**
1. Parameter Customization:
- Added a new parameter `set_as_index` to allow users to choose whether to set the new ID column as the index. Defaults to `True`.

Enhance add_ids function: Parameter customization and improved default column name

---

LICENSE.md
src/eda_toolkit/main.py

1. **Error Handling for Columns**:
- Added a check to ensure at least one column is specified.
- Updated the function to accept a single column as a string or multiple columns as a list.
- Updated the function to raise a `ValueError` if no columns are provided or if `cols` is not correctly specified.
2. **Function Parameters**:
- Changed the parameters from `col1` and `col2` to a single parameter `cols` which can be either a string or a list.
3. **Error Handling for `SortBy`**:
- Renamed `SortBy` to `sort_by` to standardize nomenclature.
- Added a check to ensure `sort_by` is either 0 or 1.
- Updated the function to raise a `ValueError` if `sort_by` is not 0 or 1.
5. **Sorting Logic**:
- Updated the sorting logic to handle the new `cols` parameter structure.
6. **Handling Categorical …

Contingency table updates

---

src/eda_toolkit/main.py

This pull request updates the `add_ids()` function to enhance its functionality by:
- Ensuring that each generated ID starts with a non-zero digit.
- Adding a check to verify that the DataFrame index is unique.
- Printing a warning message if duplicate index entries are found.
These changes improve the robustness of the function, ensuring that the IDs generated are always unique and valid, and provide necessary feedback when the DataFrame index is not unique.
- Before generating IDs, the function now checks if the DataFrame index is unique.
- If duplicates are found, a warning is printed along with the list of duplicate index entries.
- The ID generation process is updated to ensure that the first digit of each ID is always non-zero.
- A set is used to store the generated IDs, ensuring …

updated add_ids to ensure unique ids and idx check

---

src/eda_toolkit/main.py

This pull request updates the `kde_distributions()` function to enhance its capabilities and customization options for generating KDE and histogram distribution plots.
1. **Alpha Transparency for Histogram Fill**:
- Added a `fill_alpha` parameter to control the transparency of the histogram bars' fill color.
- The default value is `0.6`. An exception is raised if `fill=False` and `fill_alpha` is specified.
2. **Custom Font Sizes**:
- Introduced `label_fontsize` and `tick_fontsize` parameters to allow control over the font size of axis labels and tick marks independently.
3. **Scientific Notation Toggle**:
- Added a `disable_sci_notation` parameter to enable or disable scientific notation on axes.
4. **Improved Error Handling**:
- Added validation for the `stat` parameter to ensure that …

refined kde_distributions() w/ better error handling and addtl params

---

src/eda_toolkit/main.py

- Added `xlim` and `ylim` inputs to control x and y-axis limits of `box_violion_plot()`

added x and y limits to box_violin_plot()

---

src/eda_toolkit/main.py

Added `xlim` and `ylim` input parameters to `stacked_crosstab_plot()` to give users more flexibility on controlling axes limits

added xlim and ylim params to stacked_crosstab_plot()

---

src/eda_toolkit/main.py

Added `xlim` and `ylim` inputs to allow user to customize axes limits in `kde_distribution()`

added xlim and ylim inputs in kde_distribution()

---

src/eda_toolkit/main.py

This PR addresses inconsistencies in font sizes and text wrapping across various plot elements in the `stacked_crosstab_plot` function. The following updates have been implemented to ensure uniformity and improve the readability of plots:
1. **Title Font Size and Text Wrapping:**
- Added a `text_wrap` parameter to control the wrapping of plot titles.
- Ensured that title font sizes are consistent with axis label font sizes by explicitly setting the font size using `ax.set_title()` after plot generation.
2. **Legend Font Size Consistency:**
- Incorporated `label_fontsize` into the legend font size by directly setting the font size of the legend text using `plt.setp(legend.get_texts(), fontsize=label_fontsize)`.
- This ensures that the legend labels are consistent with the title and axis …

re-scaled fontsize for title and legend; added textwrap

---

src/eda_toolkit/main.py

This PR introduces a new function, `flex_corr_matrix`, which allows users to generate both full and upper triangular correlation heatmaps with a high degree of customization. The function includes options to annotate the heatmap, save the plots, and pass additional parameters to `seaborn.heatmap()`.
- **New Function**: `flex_corr_matrix`
- **Functionality**:
- Generates a correlation heatmap for a given DataFrame.
- Supports both full and upper triangular correlation matrices based on the `triangular` parameter.
- Allows users to customize various aspects of the plot, including colormap, figure size, axis label rotation, and more.
- Accepts additional keyword arguments via `**kwargs` to pass directly to `seaborn.heatmap()`.
- Includes validation to ensure the `triangular`, `annot`, and …

added new func for plotting corr matrices

---

setup.py
src/eda_toolkit/__init__.py
src/eda_toolkit/main.py
src/eda_toolkit/ml_eda.py

This PR introduces two new functions to enhance the visualization capabilities of our machine learning models:
1. **`plot_3d_pdp`**: This function generates 3D partial dependence plots for two features of a trained machine learning model. It supports both static visualizations using Matplotlib and interactive plots using Plotly. Key features include customizable labels, color maps, and various options for saving the plots in different formats.
2. **`plot_2d_pdp`**: This function generates 2D partial dependence plots for specified features using a trained machine learning model. It offers flexibility in the layout (grid or individual plots) and supports customization of figure size, font size, and saving options.
- **Compatibility**: Both functions are designed to be compatible with …

added 2 new functions for modeling eda; plot_3d_pdp, plot_2d_pdp

---

README_min.md
setup.py
src/eda_toolkit/__init__.py
src/eda_toolkit/ml_eda.py

- **`plot_3d_pdp` Function:**
- **Added `show_modebar` Parameter:** Introduced a new boolean parameter, `show_modebar`, to allow users to toggle the visibility of the mode bar in Plotly interactive plots.
- **Custom Margins and Layout Adjustments:**
- Added parameters for `left_margin`, `right_margin`, and `top_margin` to provide users with more control over the plot layout in Plotly.
- Adjusted default values and added options for better customization of the Plotly color bar (`cbar_x`, `cbar_thickness`) and title positioning (`title_x`, `title_y`).
- **Plotly Configuration:**
- Enhanced the configuration options to allow users to enable or disable zoom functionality (`enable_zoom`) in the interactive Plotly plots.
- Updated the code to reflect these new parameters, allowing for greater …

pdp_plots:  Minor bug fixes, enhancements, and testing improvements.

---

src/eda_toolkit/main.py
src/eda_toolkit/ml_eda.py

- **Added** `import itertools` alongside `from itertools import combinations` for consistency.
- **Added** `import math` for calculating ceiling on `num_plots` over `n_cols` in `scatter_fit_plot`
- **Statistical Overlays:**
- Added `plot_mean` and `plot_median` parameters to overlay mean and median lines on the plots.
- Added `std_dev_levels` and `std_color` parameters to overlay standard deviation bands.
- Added a `label_names` parameter to allow custom labels for variables.
- Updated the code to use `label_names` for labels on axes and in titles.
- **Log Scaling:**
- Title control adjustments for `log_scale_vars`, giving (Log) title and axis labels
- **Legend Placement:**
- Added the legend with `ax.legend(loc="best")` to place it in the best location.
- **Grid Size and Figure Size …

Method updates

---

setup.py
src/eda_toolkit/main.py

Updated set_title to "Scale Conversion" and enabled appending the scale_version value, to be appended to new dataframe, e.g., for dataframe by the name of df_test, and feature name of 'total_sales", and scale_conversion variable value of = "cutoff_0_1" will create the new column as df_test.total_sales_cutoff_0_1

New function data doctor

---

README_min.md
pyproject.toml
setup.py
src/eda_toolkit/__init__.py
src/eda_toolkit/main.py

Increased figsize to 18, 5, to accommodate the histplot as a third plot.

Added histplot to data_doctor output

---

src/eda_toolkit/main.py

"new_col_name" logic for when scale_conversion==None, but there are cutoffs to be applied to a new column, allowing such situations to go through so that the new column is created

new_col_name logic for when scale_conversion==None

---

src/eda_toolkit/main.py

In this PR, I have made the following changes:
- Moved the `PowerTransformer` import to the top of the file for consistency with the other imports.
- Added a custom `ValueError` to check if the logit transformation is applied to values between 0 and 1, as required by the logit function. A suggestion is included to use min-max scaling if values fall outside this range.
---
1. **Moved PowerTransformer import to the top:**
```python
from sklearn.preprocessing import PowerTransformer
```
2. **Added the custom exception for logit transformation:**
```python
if scale_conversion == "logit":
if np.any((sampled_feature <= 0) | (sampled_feature >= 1)):
raise ValueError(
"Logit transformation requires values to be between 0 and 1. "
"Consider using a scaling method such as min-max scaling first."
) …
```

Add logit transformation check and move PowerTransformer import

---

src/eda_toolkit/main.py

- Added user flexibility to pass input to change default 3rd plot from `boxplot` to `violinplot` in new `box_violin`; 
- changed name `box_kws` to `box_violin_kws`

Data doctor boxplot fix

---

src/eda_toolkit/main.py

This PR introduces several updates and new features to the `data_doctor` function, enhancing its flexibility and functionality:
- **`xlim`, `kde_ylim`, `hist_ylim`, and `box_violin_ylim`:**  
Allows user-specified axis limits for plots. 
- `xlim` applies to all three plot types (KDE, histogram, and box/violin plots).
- Separate y-axis limits for KDE, histogram, and box/violin plots using the respective `*_ylim` parameters.
- **`random_state`:**  
Added to control the random seed for reproducibility during data sampling.
- **Support for kwargs in `scale_conversion`:**  
Users can now pass keyword arguments (`scale_conversion_kws`) directly to transformation functions, providing greater control over transformations like `boxcox`, `logit`, `robust`, and others.
- **`RobustScaler` for …

Data doctor seed

---

src/eda_toolkit/main.py

This PR updates the `add_ids` function to improve performance, efficiency, and consistency in ID generation. The changes include:
1. **Switched to NumPy for Random Seed Handling:**
- Previous version used `random.seed(seed)` from Python's random module.
- Updated version uses `np.random.seed(seed)` for better control and reproducibility.
2. **Improved ID Generation Method:**
- Previous version generated IDs using a while loop and Python's `random.choice`.
- Updated version leverages NumPy's `np.random.choice` and vectorized operations to generate IDs more efficiently.
3. **Enhanced Efficiency:**
- Removed the while loop for generating unique IDs, replacing it with a vectorized approach using NumPy arrays.
- Generates the first digit (non-zero) and remaining digits in one step using NumPy, …

Add IDs Function - Update PR

---

src/eda_toolkit/main.py

This PR addresses issues related to the Box-Cox transformation implementation, providing more robust error handling and flexibility when applying transformations with or without additional parameters (`kwargs`). It replaces the previous approach, which mishandled confidence intervals for lambda and created compatibility issues when certain `kwargs` were missing.
- Fixed Box-Cox Transformation:
- Applied a more flexible method for handling both simple and complex cases of Box-Cox transformations (i.e., whether or not `alpha` is provided).
- Improved handling of transformation results when a confidence interval for `lambda` is returned.
- Ensured that error messages are descriptive and relevant for any potential `ValueError` raised during transformation.
- Added safeguards:
- Added checks …

Fix Box-Cox Transformation Handling and Improve Error Checking

---

src/eda_toolkit/main.py

This PR introduces enhancements to the `data_doctor` function, specifically around the handling of the Box-Cox transformation. The key changes involve:
1. **Box-Cox Transformation Enhancements**:
- Added support for `alpha` in `scale_conversion_kws` to compute and display the confidence interval for lambda during Box-Cox transformation.
- If `alpha` is provided, the confidence interval for lambda is printed.
- If `lmbda` is provided, the specific lambda value is used and printed.
2. **Updates to New Column Handling**:
- When applying Box-Cox transformation and creating a new column in the DataFrame, the lambda or confidence interval will now be displayed as part of the output summary.
3. **Docstring Update**:
- The function’s docstring was updated to reflect the changes, clarifying that: …

Enhance `data_doctor` to Support Box-Cox Transformation Confidence Intervals

---

src/eda_toolkit/main.py

This PR introduces several enhancements to the `data_doctor` function, focusing on increased customization for plot types, consistent display of cutoff information, and improved file-saving options. Key changes include:
1. **New `plot_type` Parameter**: Added a `plot_type` input to allow users to specify which plot(s) to display. Users can choose `"all"`, `"kde"`, `"hist"`, or `"box_violin"`, offering flexibility to generate specific visualizations based on their needs. If an invalid option is passed, a `ValueError` is raised.
2. **Universal Cutoff Text Display**: The lower and upper cutoff values are now displayed in all cases, regardless of the `plot_type` selected, ensuring that this important information is always visible.
3. **Dynamic Plot Type Filenames**: When saving plots, the …

 Enhance `data_doctor` Function with Plot Customization, `plot_type` Input, and Improved Save Options

---

.gitignore
src/eda_toolkit/main.py

- Refactored `tqdm` progress bar in `scatter_fit_plot` to track the overall plot-saving process, covering both individual and grid plots.
- Updated `tqdm` progress bar description in `scatter_fit_plot` to use universal phrasing: "Saving scatter plot(s)."
- Ensured consistency for singular or multiple plot-saving scenarios in progress tracking.

updated tqdm saving logic in scatter_fit_plot

---

src/eda_toolkit/main.py

This PR introduces several enhancements to improve the usability and flexibility of various plotting functions.
- Applied `text_wrap` to functions where axis label text wrapping is beneficial:
- `scatter_fit_plot`
- `box_violin_plot`
- `kde_distributions`
- **New Inputs**:
- `cbar_padding`: Controls the padding between the heatmap and the colorbar.
- `cbar_width_ratio`: Defines the relative width of the colorbar compared to the heatmap.
- **Colorbar Customization**:
- Made the colorbar optional with the `show_colorbar` parameter.
- Aligned the colorbar height with the plot for improved layout and visual consistency.
- Improved readability of plots with long titles or axis labels.
- Greater control over the appearance of the colorbar in `flex_corr_matrix`.
- Enhanced layout and …

Enhanced Plotting (+) Text Wrap Functionality

---

py_example_notebooks/adult_income_data_management.ipynb

added sklearn import

---

src/eda_toolkit/main.py

Changed dataframe_columns name to dataframe_profiler

Changed dataframe_columns name to dataframe_profiler

---

requirements.txt
src/eda_toolkit/art.py
src/eda_toolkit/main.py
src/eda_toolkit/ml_eda.py
unittests/test_art.py
unittests/test_main.py
unittests/test_ml_eda.py

- Added substantial amount of unit tests using `pytest` and `pytest-cov`:
- `unittests/test_art.py`
- `unittests/test_main.py`
- `unittests/test_ml_eda.py`
Coverage Report Shows 70% Coverage:

Unit Tests LS

---

src/eda_toolkit/data_manager.py
unittests/test_data_manager.py
unittests/test_plots.py

1. Thousand-separator support for dynamic group columns
We now include the two group-by columns (e.g. `<=50K (n = 37,155)` and `>50K (n = 11,687)`) in our integer-formatting step. That means any time you run:
```python
generate_table1(df, groupby_col="income", …)
```
2. Automatic pretty-printing with `TableWrapper`
At the end of `generate_table1()`, we wrap any returned DataFrame(s) in your existing `TableWrapper`. Its ` __str__ calls` `table1_to_str()`, so a plain:
```python
t1 = generate_table1(df, groupby_col="income")
print(t1)
```
3. Updated unittests; 81% coverage:
```text
---------- coverage: platform linux, python 3.11.11-final-0 ----------
Name                              Stmts   Miss  Cover
-----------------------------------------------------
src/eda_toolkit/__init__.py …
```

 Enhance Table 1 formatting and pretty-printing
